use org_uni_ids;

insert into cid (company_id, organization) values
("8A34BC","Fiberworks AS"),
("CAC87E","Allen Organ Company"),
("FA073E","NBASE-T Alliance"),
("FA556F","SymbolicIO"),
("7A4BA4","Innostor Technology Corporation"),
("6AE64A","S&O Electronics (Malaysia) Sdn. Bhd."),
("EA34B4","ThinkRF Inc."),
("FA63E1","Samsung Electronics (UK) Ltd"),
("EAE0D9","Berk-tek LLC"),
("FA1466","Allegion PLC"),
("8AB3DA","HomePlug Powerline Alliance, Inc."),
("CAE505","Mobilitie"),
("FAE190","IN WIN DEVELOPMENT INC."),
("8A00B0","Eoptolink Technology Inc. Ltd,"),
("3ABA37","Cirrent"),
("7AAB77","Orange"),
("DAA119","Google, Inc."),
("6A737D","25G Ethernet Consortium"),
("FA4C77","OCCITALINE"),
("2AFD6A","Charter Communications"),
("FA610E","Laboratory for Computational Sensing and Robotics, Johns Hopkins University"),
("DA28EC","HG Genuine"),
("FAF9C0","RAID Incorporated"),
("9AD263","FirmTek, LLC"),
("9A564B","Cubix Corporation"),
("1A75FB","AUTOSAR"),
("9AADCA","Credo"),
("8ADA26","Eleven Inc."),
("8AC72E","Roku, Inc."),
("AA0F85","Yamaichi Electronics"),
("CA446C","Cypress Computer Systems, Inc."),
("DAFF6B","Team Precision Public Company Limited"),
("0A8736"," IEEE 1901 Working Group"),
("DA2BDD","AT&T, Inc."),
("4A191B","ZigBee Alliance"),
("4A7206","CAIRE, Inc."),
("9AB2F8","SFF Committee"),
("4ADA10","Emotiva Audio Corp"),
("EA9FB1","Philips International B.V."),
("9A1B22","InfoCore Co.,Ltd."),
("3A5E03","Cirrus Data Solutions, Inc"),
("8ACBA4","Honeywell HSG"),
("DA9F19","neXus ID Solutions AB");