use org_uni_ids;

insert into mam (company_id, organization) values
("1C8776","Qivivo"),
("1C8776","RDP.RU"),
("1C8776","Guangzhou Video-Star Electronics Co.,Ltd."),
("8439BE","Neat S.r.l."),
("8439BE","Diamond Products LLC"),
("8439BE","ShenZhen Fudeyu Technology co.,Ltd"),
("1C8879","Xingtera China Ltd"),
("40A36B","National Research Council of Canada"),
("1C8776","Ibeo Automotive Systems GmbH"),
("40A36B","Bixi Systems Ltd."),
("70886B","Beijing Strongleader Science & Technology Co., Ltd."),
("800A80","Shenzhen Zidoo Technology Co., Ltd."),
("800A80","Dongguan I-Chime electrinics Co.,Ltd"),
("1C21D1","Soundtrack Your Brand Sweden AB"),
("DC4427","Pyrexx Technologies GmbH"),
("CC1BE0","Cassia Networks"),
("CC1BE0","i-Trinetech Co.,Ltd."),
("CC1BE0","Earphone Connection, Ubc."),
("A03E6B","Business Support Consultant Co.,Ltd"),
("C88ED1","Focalcrest, Ltd."),
("C88ED1","Comlab AG"),
("A03E6B","Shenzhen Neostra Technology Co.Ltd"),
("78C2C0","Huwomobility"),
("78C2C0","XRONOS-INC"),
("B437D1","NANJING PUTIAN TELECOMMUNICATIONS TECHNOLOGY CO.,LTD."),
("B437D1","GE Power Management"),
("DC4427","General Microsystems Sdn Bhd"),
("78C2C0","Beijing Coilabs technology co.,ltd"),
("78C2C0","ShenZhen TuLing Robot CO.,LTD"),
("B0C5CA","RISECOMM  (HK) TECHNOLOGY CO. LIMITED"),
("B0C5CA","LOWOTEC GmbH"),
("807B85","EFCO"),
("807B85","Chendu Ningshui Technology Co.,Ltd"),
("807B85","Shiroshita Industrial Co., Ltd."),
("80E4DA","Beijing Gaokezhongtian Technology Co Ltd"),
("2CD141","Beijing Hexing Chuangxiang Technology Co., Ltd."),
("1CCAE3","eSight Corporation"),
("1CCAE3","Gahdeung Elecom"),
("64FB81","Bronkhorst High-Tech BV"),
("64FB81","Dongyang unitech.co.ltd"),
("64FB81","XIMO Communication Technology Co., Ltd"),
("64FB81","Narrative AB"),
("549A11","SpearX Inc."),
("549A11","Torrap Design Limited"),
("807B85","Ningbo Plus and Popscreens electronic Technology Co.,LTD"),
("1CCAE3","PGA ELECTRONIC"),
("1CCAE3","Private"),
("80E4DA","EVER Sp. z o.o."),
("80E4DA","Shortcut Labs"),
("B437D1","DIMTON CO.,LTD."),
("B437D1","Lezyne INC USA"),
("74F8DB","Capwave Technologies Inc"),
("885D90","Wuhan Strong Electronics Co., Ltd"),
("549A11","Xi'an Hua Fan Technology Co.,Ltd."),
("549A11","Elite Silicon Technology, Inc."),
("74F8DB","InnoTrans Communications"),
("885D90","Hexaglobe"),
("885D90","Gigatech R&D Corp."),
("F80278","Innodisk"),
("0CEFAF","Infinisource Inc."),
("90C682","ekey biometric systems gmbh"),
("2C6A6F","Holjeron"),
("2C6A6F","Logic IO Aps"),
("2C6A6F","Wellntel, Inc."),
("9802D8","HANSHIN MEDICAL CO., LTD."),
("9802D8","Ormazabal Protection&Automation"),
("0CEFAF","BSX Athletics"),
("0CEFAF","PREMIUM SA"),
("0CEFAF","Sentry360"),
("A44F29","Shenzhen Huadoo Bright Group Limitied"),
("A0BB3E","WiteRiver Technology LLC"),
("28FD80","Grandway Technology (Shenzhen) Limited"),
("28FD80","Airbus Defence and Space Oy"),
("28FD80","JINLITONG INTERNATIONAL CO.,LTD"),
("28FD80","Zhixiang Technology Co., Ltd."),
("A0BB3E","Filo SRL"),
("9802D8","United Power Research Technology Corp."),
("A0BB3E","AutarcTech GmbH"),
("A0BB3E","COMSYS Communications Systems Service GmbH"),
("90C682","Shanghai HuRong Communication Technology Development Co., Ltd."),
("90C682","ACT"),
("F80278","Lit Technologies"),
("F80278","Rosemount Analytical"),
("F80278","BETTINI SRL"),
("28FD80","NUUO, Inc."),
("E81863","WETEK ELECTRONICS LIMITED"),
("E81863","AVCON Information Technology Co.,Ltd"),
("B8D812","Lam Research"),
("B8D812","Vonger Electronic Technology Co.,Ltd."),
("B8D812","V5 Technology Corporation"),
("74E14A","Emerging Technology (Holdings) Ltd."),
("74E14A","emz-Hanauer GmbH & Co. KGaA"),
("E4956E","Shanghai Tieda Telecommunications Equipment Co.,LTD."),
("D02212","RHENAC Systems GmbH"),
("E81863","DIGITAL DYNAMICS, INC."),
("E81863","BSM Wireless Inc."),
("D02212","SHENZHEN ZHONGXI SECURITY CO.,LTD"),
("E4956E","Red Point Positioning, Corp."),
("E4956E","Guang Lian Zhi Tong Technology Limited"),
("B8D812","Glamo Inc."),
("74E14A","AStar Design Service Technologies Co., Ltd."),
("A44F29","Protean Payment"),
("A44F29","Dermalog Identification Systems GmbH"),
("3C39E7","MARPOSS SPA"),
("3C39E7","VANSTONE ELECTRONIC (BEIJING)CO,. LTD."),
("3C39E7","HomeWizard B.V."),
("D02212","URANO INDUSTRIA DE BALANCAS E EQUIPAMENTOS LTDA"),
("BC6641","UtilLighting Co.,Ltd."),
("BC6641","Shenzhen General Measure Technology Co., Ltd"),
("BC6641","Intuitive Surgical, Inc"),
("BC3400","IPLINK Technology Corp"),
("A43BFA","The Magstim Company Ltd."),
("A43BFA","Plus One Japan Ltd."),
("BC6641","Global China Technology Limited"),
("B01F81","SHENZHEN GRID TECHNOLOGY CO.,LTD"),
("B01F81","Uvax Concepts"),
("F40E11","Elektronika Naglic d.o.o."),
("F40E11","Axel srl"),
("7C70BC","dogtra"),
("7C70BC","Canary Connect, Inc."),
("141FBA","Wisnetworks Technologies Co., Ltd."),
("7C70BC","HOPERUN MMAX DIGITAL PTE. LTD."),
("7C70BC","Shanghai magcomm communication technology co ltd"),
("BC3400","FARO TECHNOLOGIES, INC."),
("BC3400","Q-PRODUCTS a. s."),
("B01F81","TAIWAN Anjie Electronics Co.,Ltd."),
("7419F8","Broadanet S.T.M"),
("A43BFA","Deatronic srl"),
("A43BFA","Powell Industries"),
("D07650","Revox Inc."),
("D07650","InventDesign"),
("D07650","TAPKO Technologies GmbH"),
("1C8774","SIGFOX"),
("1C8774","Silora R&D"),
("1C8879","SHENZHENFREELINK ELECTRONIC CO.,LTD"),
("1C8879","Accriva"),
("1C8779","Istria soluciones de criptografia, S. A."),
("1C8774","Wide World Trade HK ltd."),
("1C8774","HABEY USA Inc."),
("1C8879","Ultraflux"),
("1C8879","Eolos IT Corp"),
("1C8774","Quest Integrity"),
("78CA83","Pinhole (Beijing) Technology Co., Ltd."),
("78CA83","Konecranes"),
("38B8EB","ExaScaler Inc."),
("38FDFE","New Garden Co., Ltd."),
("38FDFE","CaptiveAire Systems Inc."),
("5CF286","Access IS"),
("5CF286","Shanghai Notion Information Technology CO.,LTD."),
("5CF286","Sunpet Industries Limited"),
("5CF286","VPInstruments"),
("5CF286","Unfors Raysafe AB"),
("7C477C","Midwest Microwave Solutions"),
("5CF286","Daisen Electronic Industrial Co., Ltd."),
("7C477C","Photosynth Inc."),
("986D35","iWave Japan, Inc."),
("986D35","Zhejiang Hanshow Technology Co., Ltd."),
("50FF99","Goetting KG"),
("50FF99","Garrison Technology"),
("50FF99","Honeywell International"),
("50FF99","Sichuan Dowlab Electronics Technology Co. Ltd"),
("E0B6F5","Shenzhen Civicom Technology Co.,Limited"),
("E0B6F5","BeSTAR Corporation"),
("E0B6F5","Shenzhen Xrinda Technology Ltd"),
("E0B6F5","Moog Crossbow"),
("E0B6F5","funktel GmbH"),
("C47C8D","LYNX INNOVATION LITIMED"),
("C47C8D","ROBOSTAR"),
("C47C8D","Awiselink Co., Ltd."),
("C47C8D","Watec Co., Ltd."),
("CCD31E","Rondo Burgdorf AG"),
("CCD31E","BBPOS International Limited"),
("CCD31E","KEN A/S"),
("D0D94F","Hangzhou xiaoben technology co.,Ltd"),
("D0D94F","Private"),
("D0D94F","Perfant Technology Co., Ltd"),
("8C192D","Pyras Technology Inc."),
("8C192D","Charmlink Tech(HK) Co.,Limited "),
("8C192D","Elcon AB"),
("283638","Dspread Technology (Beijing) Inc."),
("283638","Bluekey Pty Ltd"),
("CC1BE0","Private"),
("F40E11","Private"),
("D07650","Private"),
("E81863","Private"),
("3C39E7","Private"),
("F80278","Private"),
("9802D8","Private"),
("90C682","Private"),
("283638","APPEAK Technology System Co.Ltd."),
("1CCAE3","Private"),
("283638","Shenzhen  Zhi Hua  Creative Technology  Co., Ltd."),
("B0C5CA","SHENZHEN KTC TECHNOLOGY GROUP "),
("283638","SCA Hygiene Products AB"),
("F0ACD7","Med-Pat/Inn-Phone"),
("F0ACD7","PAVO TASARIM URETIM TICARET A.S."),
("283638","SHENZHEN GOSPELL SMARTHOME ELECTRONIC CO., LTD."),
("F0ACD7","Smart Power Technology Co., Ltd."),
("F0ACD7","Hanju Network Technologies Co."),
("58E876","Chengdu Vision-Zenith Technology Co.,Ltd"),
("58E876","DivioTec Inc."),
("84E0F4","Orchard Electronics Co., Ltd."),
("84E0F4","AIMTRON CORPORATION"),
("1C8776","Strone Technology"),
("1C8779","BEIDIAN  GROUP"),
("1C8779","Beijing Geedeen Technology Co., Ltd"),
("1C8779","Novetta"),
("1C8779","SMARTMOVT TECHNOLOGY Co.， LTD"),
("1C8779","A-GEAR COMPANY LIMITED "),
("8439BE","Shenzhen Lidaxun Digital Technology Co.,Ltd"),
("8439BE","Guangdong SunMeng Information Technology Co. Ltd."),
("8439BE","EDC Electronic Design Chemnitz GmbH"),
("8439BE","Emotiq s.r.l."),
("40A36B","Embrionix Design Inc."),
("8439BE","Shenzhen Ramos Digital Technology Co,.Ltd."),
("40A36B","SKS-Kinkel Elektronik GmbH"),
("800A80","Beijing VControl Technology Co., Ltd."),
("A03E6B","Jining SmartCity Infotech Co.Ltd."),
("C88ED1","Shanghai Bwave Technology Co.,Ltd"),
("C88ED1","Advanced Micro Controls Inc."),
("C88ED1","Shenyang Machine Tool(Group) Research & Design Institute Co., Ltd, Shanghai Branch"),
("CC1BE0","ART&CORE Inc"),
("CC1BE0","Sichuan Dianjia network technology Co.Ltd."),
("CC1BE0","MICROTECH SYSTEM"),
("DC4427","Suritel"),
("B0C5CA","Audio Elektronik İthalat İhracat San ve Tic A.Ş."),
("B0C5CA","D&T Inc."),
("C88ED1","AISWORLD PRIVATE LIMITED"),
("C88ED1","ROTRONIC AG"),
("1C21D1","Wuhan TieChi Detection Technology Co., Ltd."),
("DC4427","EK-TEAM Elektronik- u. Kunststoff-Technik GmbH"),
("DC4427","Shanghai Huahong Integrated Circuit Co.,Ltd"),
("A03E6B","718th  Research  Institute  of  CSIC"),
("A03E6B","iLoda Solutions Limited"),
("B0C5CA","shanghai University Ding-Tech software Corp.,ltd"),
("78C2C0","KORF Inc."),
("78C2C0","Ombitron, Inc."),
("78C2C0","Ningbo Sanxing Electric Co., Ltd."),
("B437D1","Union Tecnologica Noxium S.L."),
("B437D1","Nanjing yuekong Intelligent Technology"),
("885D90","Hi-Profile Achievement (M) Sdn Bhd"),
("885D90","FOSHAN HUAGUO OPTICAL CO.,LTD"),
("74F8DB","Songam Syscom Co. LTD."),
("74F8DB","Shenzhen Melon Electronics Co.,Ltd"),
("885D90","Premier Merchandises Limited"),
("B437D1","Stratom, Inc."),
("74F8DB","TBM CO., LTD."),
("2C6A6F","Shanghai Shuncom Electronic Technology Co.,Ltd"),
("2C6A6F","ELKO EP, s.r.o."),
("9802D8","Private"),
("549A11","Hangzhou duotin Technology Co., Ltd."),
("549A11","VendNovation LLC"),
("549A11","Royal Boon Edam International BV"),
("549A11","Shenzhen Excera Technology Co.,Ltd."),
("807B85","Mersen"),
("807B85","SMART ELECTRONICS NZ LIMITED"),
("1CCAE3","Insigma Inc"),
("80E4DA","Neutronics"),
("1CCAE3","Dabi Atlante S/A Industrias Medico Odontológicas"),
("1CCAE3","Dream Visions Co., LTD"),
("1CCAE3","SIREA"),
("2CD141","Minno LLC"),
("90C682","Lachmann & Rink GmbH"),
("80E4DA","Wheatstone Corporation"),
("64FB81","hiQview Corporation"),
("64FB81","Pricer AB"),
("90C682","S.A.E.T. S.R.L."),
("90C682","Cinet Inc"),
("90C682","Shenzhen Lencotion Technology Co.,Ltd"),
("2C6A6F","Sensity Systems"),
("2C6A6F","Schneider Electric Korea"),
("2C6A6F","Milbank Manufacturing Co."),
("807B85","Zhuhai TOP Intelligence Electric Co., Ltd."),
("A0BB3E","Shenzhen Talent Technology company limited"),
("9802D8","Zedi, Inc."),
("28FD80","Jasco Products Company"),
("28FD80","Galileo, Inc."),
("2C265F","Itus Networks, LLC"),
("0CEFAF","Rotel"),
("0CEFAF","Firmware Design AS"),
("A44F29","Certi Networks Sdn Bhd"),
("A44F29","Comsel System Ltd"),
("A44F29","Shanghai KuanYu Industrial Network Equipment Co.,Ltd"),
("100723","First Chair Acoustics Co., Ltd."),
("100723","Audio Engineering Ltd."),
("2C265F","Motec GmbH"),
("F80278","Electric Objects"),
("A0BB3E","Link Labs"),
("28FD80","Poket Hardware GmbH"),
("3C39E7","ELSA Japan Inc."),
("E4956E","PT.MLWTelecom"),
("E4956E","NationalchipKorea"),
("E4956E","Shanghai Hoping Technology Co., Ltd."),
("E4956E","Tband srl"),
("E81863","Siliconcube"),
("E81863","DigiMagus Technology (Shenzhen) Co., Ltd"),
("B8D812","Entotem LTD"),
("74E14A","Wuhan Shenghong Laser Projection Technology Co.,LTD"),
("B01F81","Advanced & Wise Technology Corp."),
("B01F81","Steffens Systems GmbH"),
("D02212","GNS-GmbH"),
("D02212","UAB &quot;SALDA&quot;"),
("D02212","Viatron GmbH"),
("D02212","Spirit IT B.V."),
("E81863","JDM Mobile Internet Solution(Shanghai) Co., Ltd."),
("BC6641","Solectria Renewables, LLC"),
("58FCDB","Timex Group USA Inc"),
("58FCDB","Open Roads Consulting, Inc."),
("BC6641","Sidus Novum Sp. z o. o."),
("74E14A","aritec gmbh"),
("74E14A","Cerevo Inc."),
("D07650","Electro-Motive Diesel"),
("D07650","ENCORED Technologies, Inc."),
("D07650","Annapurna Labs"),
("141FBA","Thales Communications & Security SAS"),
("7C70BC","Digital Lumens"),
("BC3400","LLD Technology Ltd."),
("BC3400","Hangzhou Linker Digital Technology Co., Ltd"),
("BC3400","Shenzhen PHilorise Technical Limited"),
("A43BFA","SHEN ZHEN PASUN TECH CO.LTD."),
("A43BFA","BOI Solutions"),
("A43BFA","Beijing Uniwill Science and Technology Co,Ltd"),
("D07650","DAIKEN AUTOMACAO LTDA"),
("7419F8","Bach Icon ApS"),
("7C70BC","Lukup Media"),
("7C70BC","Bidgely"),
("F40E11","BRADAR INDUSTRIA SA"),
("F40E11","Shenzhen Grandsun Electronic Co.,Ltd."),
("F40E11","E-SONG"),
("F40E11","realphone technology co.,ltd"),
("BC3400","Dexcel Design Pvt Ltd"),
("B01F81","Technion Oy"),
("7419F8","Tanjarine"),
("7419F8","Essential Trading Systems Corp"),
("7419F8","Marmitek"),
("1C8779","ASSYSTEM France"),
("1C8879","ANDRA Sp. z o.o."),
("1C8774","Weber Marking Systems GmbH"),
("1C8774","New Nordic Engineering"),
("1C8879","Sensys Networks, Inc."),
("1C8879","gekartel AG"),
("78CA83","Nomiku"),
("78CA83","APC"),
("78CA83","IHM"),
("78CA83","Louroe Electronics"),
("78CA83","Elanview Technology Co.,Ltd"),
("38B8EB","CeeNex Inc"),
("38B8EB","Yellowbrick Data, Inc."),
("38B8EB","MATRIXSTREAM TECHNOLOGIES, INC."),
("38B8EB","barox Kommunikation GmbH"),
("38B8EB","Ajax Systems Inc"),
("38B8EB","Wyres SAS"),
("38FDFE","WAYTONE (BEIIJNG) COMMUNICATIONS CO.,LTD"),
("38FDFE","iSmart electronic technology co.,LTD"),
("38FDFE","Indra Navia AS"),
("5CF286","CHIPSEN Co.,Ltd."),
("5CF286","SHENZHEN HIVT TECHNOLOGY CO.,LTD"),
("7C477C","DaLian Cheering Tech Co.,Ltd"),
("7C477C","BungBungame Inc"),
("7C477C","RLC Electronics Systems"),
("7C477C","I-Convergence.com"),
("986D35","Praesideo B.V."),
("986D35","Beijing 3CAVI Tech Co.,Ltd"),
("986D35","Shenzhen MALATA Mobile Communication Co.,LTD"),
("986D35","blossom communications corp."),
("50FF99","Dolphin Concepts Limited"),
("50FF99","Shenzhen Haipengxin Electronic Co., Ltd."),
("50FF99","Yongjing Shanghai Electronic Science and Technology "),
("50FF99"," SHENZHEN KINGVT ELECTRONICS CO.,LTD"),
("E0B6F5","Folksam AB"),
("E0B6F5","Agora"),
("E0B6F5","Advatek Lighting Pty Ltd"),
("6891D0","Multi Alarm Zrt."),
("6891D0","Spraying Systems Co."),
("C47C8D","GETEMED Medizin- und Informationstechnik AG"),
("C47C8D","GC AUTOMATION CO,LTD"),
("C47C8D","Silvus technologies inc"),
("CCD31E","SAMIM Co"),
("CCD31E","Fluidic Energy"),
("CCD31E","NTmore.Co.,Ltd"),
("CCD31E","Siemens AG, MO MLT BG"),
("D0D94F","MAX Smart Home, LLC"),
("D0D94F","Optigo Networks"),
("D0D94F","Teco Image Systems Co., Ltd."),
("8C192D","Greenfield Technology"),
("8C192D","Shenzhen Huanuo Internet Technology Co.,Ltd"),
("D02212","Private"),
("100723","Private"),
("B0C5CA","Private"),
("283638","Sabinetek"),
("283638","Knowles Electronics LLC"),
("8C192D","SRETT"),
("7C70BC","Private"),
("A43BFA","Private"),
("B01F81","Private"),
("0055DA","Private"),
("283638","Panasonic System Solutions Europe"),
("F0ACD7","Zhejiang Makepower Electronics,Inc."),
("84E0F4","RAY Co.,LTD"),
("84E0F4","SHENZHEN HCN.ELECTRONICS CO.,LTD."),
("F0ACD7","QUANTUM POWER SYSTEMS"),
("F0ACD7","Intenta GmbH"),
("58E876","TEM Mobile Limited"),
("58E876","Broad Air Technology Co., LTD."),
("C0D391","IXON B.V."),
("C0D391","Ernitec"),
("C0D391","Hofon Automation Co.,Ltd"),
("C0D391","Private"),
("84E0F4","ShenZhen Panrich Technology Limited"),
("1C8776","Zhuhai MYZR Technology Co.,Ltd"),
("1C8779","Visual Land Inc."),
("1C8779","Wurm GmbH & Co. KG Elektronische Systeme"),
("1C8779","TASC Systems Inc."),
("1C8779","Shenzhen Shouxin Tongda Technology Co.,Ltd"),
("1C8779","AllThingsTalk"),
("1C8776","Jiangsu ETERN COMMUNICATION Co.,ltd"),
("40A36B","Fin Robotics Inc"),
("70886B","Shenzhen Coolhear Information Technology Co., Ltd."),
("70886B","HORI CO., LTD."),
("70886B","Chengdu Ophylink Communication Technology Ltd."),
("70886B","Veracity UK Ltd"),
("8439BE","Cheng Du virtual world Technology Limited."),
("70886B","RHXTune Technology Co.,Ltd"),
("70886B","MAX4G, Inc."),
("800A80","LLVISION TECHNOLOGY CO.,LTD"),
("1C21D1","Scientific-Production Enterprise Dynamics"),
("1C21D1","Ognios GmbH"),
("DC4427","VerifEye Technologies"),
("DC4427","Wharton Electronics Ltd"),
("DC4427","Nex Technologies PTY LTD"),
("B0C5CA","SunTech Medical, Inc."),
("1C21D1","p2-plus inc."),
("1C21D1","Global Design Solutions Ltd"),
("A03E6B","Wuhan Rui Ying Tong Network Technology Co., Ltd(China)"),
("A03E6B","Friday Lab, UAB"),
("C88ED1","Aventics GmbH"),
("A03E6B","s&t embedded GmbH"),
("C88ED1","Electronic Controls Design, Inc."),
("CC1BE0","Laserworld (Switzerland) AG"),
("CC1BE0","Shenzhen Vanstor Technology Co.,Ltd"),
("0055DA","Victorsure Limited"),
("0055DA","BroadSoft, Inc."),
("0055DA","Datapath Limited"),
("0055DA","Quantum Communication Technology Co., Ltd.,Anhui"),
("0055DA","Novexx Solutions GmbH"),
("A03E6B","KoCoS Messtechnik AG"),
("DC4427","Skywave Technology Co,.Ltd."),
("B0C5CA","XMetrics"),
("CC1BE0","NEWSTAR (HK) ELECTRONIC DEVELOPMENT LIMITED"),
("CC1BE0","MobiStor Technology Inc."),
("74F8DB","Ballard Technology Inc."),
("74F8DB","WiFi Hotspots, SL"),
("74F8DB","Enercon Technologies"),
("885D90","Unitac Technology Limited"),
("885D90","iRoom GmbH"),
("B437D1","NSI Co., Ltd."),
("B437D1","Yireh Auto Tech Co.,Ltd."),
("B437D1","Fibersystem AB"),
("B437D1","Alturna Networks"),
("74F8DB","Bernard Krone Holding GmbH & Co. KG"),
("885D90","Creative Sensor Inc."),
("885D90","DAIDONG Industrial System Co., Ltd."),
("B0C5CA","IVK-SAYANY"),
("78C2C0","Wan Chao An (Beijing) Technology Co., Ltd."),
("78C2C0","Guangzhou Hongcai Stage Equipment co.,ltd"),
("549A11","Alfen BV"),
("549A11","Orient Direct, Inc."),
("549A11","Elotech Industrieelektronik GmbH"),
("78C2C0","Ory Laboratory Co., Ltd."),
("80E4DA","Krizer international Co,. Ltd."),
("80E4DA","Beijing Yuantel Technolgy Co.,Ltd-Shenzhen Branch"),
("80E4DA","Thurlby Thandar Instruments LTD"),
("2CD141","Private"),
("807B85","Oliotalo Oy"),
("807B85","Quickte Technology Co.,Ltd"),
("807B85","Hangzhou Synway Information Engineering Co., Ltd"),
("1CCAE3","OxySec S.r.l."),
("1CCAE3","TengFeng"),
("80E4DA","Akenori PTE LTD"),
("9802D8","Fritz Kuebler GmbH"),
("9802D8","SHENZHEN ATEKO PHOTOELECTRICITY CO LTD"),
("A0BB3E","Beijing Techshino Technology Co., Ltd."),
("A0BB3E","Messtechnik Sachs GmbH"),
("2CD141","Bowei Technology Company Limited"),
("2CD141","AOptix Technologies, Inc"),
("2CD141","iCIRROUND Inc"),
("2C6A6F","Beep, Inc."),
("2C6A6F","NanChang LangJie Technology Co.,Ltd"),
("9802D8","AGV spa"),
("9802D8","Simplo Technology Co.,LTD"),
("64FB81","Bridgeport Instruments, LLC"),
("64FB81","Sichuan Haige Actec Communication Technology Co.,Ltd."),
("64FB81","Securosys SA"),
("90C682","PowerShield Limited"),
("90C682","Teletek Electronics"),
("90C682","Innovative Electronic Technology"),
("64FB81","SHANGHAI   SIMCOM   LIMITED"),
("64FB81","Seven Solutions S.L"),
("28FD80","Xiaocong Network Limited"),
("2C265F","E Core Corporation"),
("2C265F","Polara Engineering"),
("2C265F","Coremate Technical Co., Ltd"),
("2C265F","shenzhen Clever Electronic Co., Ltd."),
("2C265F","XIAMEN VORLINK IOT TECHNOLOGY CO.,LTD."),
("F80278","Dueton Systems s.r.o."),
("0CEFAF","Hubei Century Network Technology Co .Ltd"),
("A44F29","Olssen B.V."),
("3C39E7","Zone Controls AB"),
("3C39E7","RO.VE.R. Laboratories S.p.A"),
("100723","TESSERA TECHNOLOGY INC."),
("100723","ESTONE TECHNOLOGY INC"),
("100723","Tongfang computer co.Ltd."),
("F80278","EMBUX Technology Co., Ltd."),
("F80278","3Shape Holding A/S"),
("F80278","Reason Tecnologia SA"),
("100723","RippleTek Tech Ltd"),
("D02212","Xperio Labs Ltd."),
("0CEFAF","Goerlitz AG"),
("A44F29","GUANGDONG REAL-DESIGN INTELLIGENT TECHNOLOGY CO.,LTD"),
("A44F29","Selektro Power Inc"),
("A0BB3E","SIMTEC Elektronik GmbH"),
("A0BB3E","DirectOut GmbH"),
("D02212","Cliptech Industria e Comercio Ltda"),
("E81863","Shenzhen Hipad Telecommunication Technology Co.,Ltd"),
("B01F81","Access Device Integrated Communications Corp."),
("B01F81","COMOTA Co., Ltd."),
("58FCDB","Hi-Target Surveying Instrument Co., Ltd."),
("58FCDB","Shenzhen Siecom Communication Technology Development Co.,Ltd."),
("58FCDB","Beseye Cloud Security Co. Ltd."),
("E4956E","ELAN SYSTEMS"),
("BC6641","Lucent Trans Electronics Co., Ltd"),
("E81863","Guangzhou Tianyi Electronics Co., Ltd"),
("E81863","DongGuan Pengxun Electronics Technology Co., Ltd."),
("B8D812","ZheJiang FangTai Electirc Co., Ltd"),
("E4956E","Shenzhen Arronna Telecom Co.,Ltd"),
("E4956E","iConservo Inc"),
("BC6641","Scientific Games"),
("BC6641","InSync Technology Ltd"),
("58FCDB","Excenon Mobile Technology Co., Ltd."),
("74E14A","open joint stock company YUG-SISTEMA plus"),
("B8D812","Kiwigrid GmbH"),
("B8D812","Neuropace Inc."),
("B8D812","iModesty Technology Corp."),
("74E14A","Diamond Kinetics"),
("A43BFA","JSC “Component-ASU”"),
("A43BFA","Recognition Systems LLC"),
("A43BFA","Circus World Displays Ltd"),
("D07650","Greenwave Scientific"),
("BC3400","AURALIC LIMITED"),
("BC3400","Cameron"),
("BC3400","LifeSmart"),
("7C70BC","K-Vision Technology (Shanghai), Ltd"),
("B01F81","Private"),
("F40E11","DXG Technology Corp."),
("F40E11","Sterna Security"),
("141FBA","BYZERO"),
("141FBA","Shenzhen Mining Technology Co.,Ltd."),
("7C70BC","Ametek VIS"),
("F40E11","Shenzhen headsun technology"),
("141FBA","POS Systema LLC"),
("141FBA","Winsonic Electronics Co., Ltd."),
("7419F8","Quest Payment Systems"),
("7419F8","Volacomm Co., Ltd"),
("7419F8","Cloudvue Technologies Corporation"),
("1C8774","Nichigaku"),
("1C8774","Ing Buero Ziegler"),
("1C8879","Airsmart System Co.,Ltd"),
("1C8879","Beijing Raycores Technology Co.,Ltd"),
("78CA83","Neofon GmbH"),
("78CA83","Excelocity Inc."),
("78CA83","Beijing CarePulse Electronic Technology "),
("78CA83","Hubei Boyuan Zhijia Network Media Co. Ltd."),
("38B8EB","Aina Wireless Inc"),
("38FDFE","FUBA Automotive Electronics GmbH"),
("38FDFE","Rademacher Geraete-Elektronik GmbH"),
("38FDFE","Siemens AG, PG IE R&D"),
("38FDFE","Edge I&D Co., Ltd."),
("5CF286","Itron UK Limited"),
("7C477C","POWERLAND LIMITED"),
("5CF286","BrightSky, LLC"),
("7C477C","EyeLock LLC"),
("7C477C","Hangzhou Yiyitaidi Information Technology Co., Ltd."),
("986D35","Shenzhen cositea electronics technology co.,LTD"),
("986D35","my-PV GmbH"),
("986D35","BAYCOM OPTO-ELECTRONICS TECHNOLGY CO., LTD."),
("50FF99","IPC Global"),
("50FF99","LEGEND WINNER LIMITED"),
("50FF99","metraTec GmbH"),
("50FF99","Informa LLC"),
("E0B6F5","ITEL MOBILE LIMITED"),
("E0B6F5","Huizhou GISUN Industrial CO. LTD"),
("6891D0","G-TECH Instruments Inc."),
("6891D0","Central Railway Manufacturing"),
("6891D0","Shenzhen NeaTech Intelligence Technology Co., Ltd."),
("6891D0","WiseCube"),
("6891D0","Altis Technology "),
("C47C8D","PASCAL Co., Ltd."),
("C47C8D","Airbus DS - SLC"),
("C47C8D","Star2Star Communications, LLC"),
("C47C8D","HHCC Plant Technology Co.,Ltd."),
("CCD31E","Elk Products"),
("CCD31E","Neptune Systems"),
("CCD31E","PJG Systementwicklung GmbH"),
("CCD31E","ShenZhenBoryNet Co.,LTD."),
("CCD31E","Shenzhen Decnta Technology Co.,LTD."),
("D0D94F","peiker CEE"),
("8C192D","You Zhengcheng co.,ltd"),
("8C192D","ViaWear, Inc."),
("BC3400","Private"),
("7419F8","Private"),
("1C21D1","Private"),
("DC4427","Private"),
("C88ED1","Private"),
("80E4DA","Private"),
("885D90","Private"),
("283638","CHARGELIB"),
("283638","ShangHai Canall Information Technology Co.,Ltd"),
("DC4427","Rohde&Schwarz Topex SA"),
("F0ACD7","Telefonix Incorporated"),
("F0ACD7","Suzhou Pairlink Network Technology"),
("F0ACD7","U3storage Technologies Co., Ltd"),
("F0ACD7","Simprints Technology Ltd"),
("58E876","McWong International Inc"),
("58E876","Chronos Technology Ltd."),
("58E876","KUSTOM SIGNALS INC"),
("58E876"," Baoruh Electronic Co., Ltd."),
("58E876","Xiamen Cacamle Technology Co.,Ltd."),
("C0D391","WiTagg, Inc"),
("58E876","PROBIT SRL"),
("C0D391","B9Creations"),
("C0D391","REGULUS CO.,LTD."),
("C0D391","Fuzhou Jinshi Technology Co.,Ltd."),
("C0D391","Alpha Audiotronics, Inc."),
("1C8776","Hekatron Vertriebs GmbH"),
("1C8779","Hangzhou Xiaowen Intelligent Technology Co., Ltd."),
("1C8779","ZHEJIANG ITENAL TECHNOLOGY CO.,LTD"),
("1C8776","Unjo AB"),
("1C8776","Corporate Systems Engineering "),
("1C8776","Tokyo Drawing Ltd."),
("8439BE","Guangzhou Heygears Technology Ltd"),
("40A36B","SFT Co., Ltd."),
("40A36B","TW-TeamWare"),
("40A36B","Omnitracs, LLC"),
("40A36B","Onion Corporation"),
("40A36B","FAOD Co.,Ltd."),
("70886B","Church & Dwight Co., Inc."),
("70886B","Cable Matters Inc."),
("800A80","Beijing Gooagoo Technical Service Co.,Ltd."),
("800A80","Sumitomo Wiring Systems, Ltd."),
("0055DA","Nanoleaf"),
("0055DA","OOO DEKATRON"),
("0055DA","LUCISTECHNOLOGIES（SHANGHAI）CO.,LTD"),
("800A80","Golana Technology (Shenzhen) Co., Ltd."),
("CC1BE0","Matter Labs Pty Ltd"),
("CC1BE0","Beijing Daotongtianxia Co.Ltd."),
("CC1BE0","IC RealTech"),
("A03E6B","Nanjing zhanyi software technology co., LTD"),
("A03E6B","Videx Electronics S.p.A."),
("A03E6B","Incogniteam Ltd."),
("B0C5CA","Astyx GmbH"),
("B0C5CA","TEM Mobile Limited"),
("DC4427","Nautilus Infotech CO., Ltd."),
("DC4427","EcoGuard AB"),
("C88ED1","PHOENIX ENGINEERING CORP."),
("C88ED1","AP Sensing GmbH"),
("C88ED1","Fibergate.Inc"),
("1C21D1","Private"),
("C88ED1","German Pipe GmbH"),
("1C21D1","Liscotech System Co., Ltd."),
("1C21D1","Microview Science and Technology Co.,Ltd"),
("1C21D1","Varaani Works Oy"),
("B0C5CA","abode systems, inc."),
("78C2C0","RONIX incorporated"),
("78C2C0","Shenzhen ELI Technology co.,ltd"),
("B437D1","ZXY Sport Tracking"),
("74F8DB","Wuhan Tianyu Information Industry Co., Ltd."),
("74F8DB","Shenzhen Ruishi Information Technology Co.,Ltd."),
("885D90","Shenzhen Speedrun Technologies Co.,Ltd."),
("78C2C0","SES"),
("B437D1","eInfochips Limited"),
("B437D1","KOMSIS ELEKTRONIK SISTEMLERI SAN. TIC. LTD.STI"),
("885D90","ShenZhen Yuyangsheng technology company LTD"),
("885D90","Shenzhen JingHanDa Electronics Co.Ltd"),
("2CD141","Shanghai RW ELE&TEC CO.,LTD"),
("2CD141","ZENIC INC."),
("90C682","Beijing Acorn Networks Corporation"),
("90C682","Nanjing Jiexi Technologies Co., Ltd."),
("64FB81","ChengDu KeChuang LongXin Sci-tech Co.,Ltd"),
("64FB81","Kay Schulze & Karsten Pohle GbR"),
("2C6A6F","EATON FHF Funke + Huster Fernsig GmbH"),
("90C682","Shenzhen Photon Broadband Technology CO., LTD"),
("2C6A6F","TINYCO"),
("2C6A6F","SHEN ZHEN SIS SCIENCE & TECHNOLOGY LTD."),
("1CCAE3","TOKAI RIKA CO., LTD."),
("1CCAE3","Bird Home Automation GmbH"),
("80E4DA","Nanjing LILO Technology Co. Ltd."),
("80E4DA","Dalian Roiland Technology Co.,Ltd"),
("80E4DA","BroadMedia Co., Ltd."),
("2CD141","CITA SMART SOLUTIONS LTD"),
("549A11","Tite, Inc."),
("549A11","Niveo International BV"),
("807B85","Kaynes Technology India Pvt Ltd"),
("807B85","IDair, LLC"),
("807B85","Quantel USA, Inc."),
("9802D8","HySecurity"),
("F80278","Witium Co., Ltd"),
("0CEFAF","CJSC «Svyaz Engineering»"),
("0CEFAF","GainStrong Industry Co.,Ltd"),
("3C39E7","BEWATEC Kommunikationstechnik GmbH"),
("100723","Wireless input technology Inc."),
("3C39E7","Hannstar Display Corp"),
("100723","Ion Professional Solutions"),
("100723","nanoTech Co., Ltd."),
("D02212","u::Lux GmbH"),
("A44F29","Innovations in Optics, Inc."),
("A44F29","DGC Access AB"),
("9802D8","Grammer EiA Electronics nv"),
("A0BB3E","Sandal Plc"),
("A0BB3E","ManTech International Corporation"),
("3C39E7","iiM AG"),
("3C39E7","chipsguide technology Co.,LTD"),
("3C39E7","Sensor to Image GmbH"),
("3C39E7","Martem AS"),
("0CEFAF","LUMEL S.A."),
("0CEFAF","Engineering Center ENERGOSERVICE"),
("A44F29","HALLIBURTON"),
("28FD80","Digital Signal Corp"),
("2C265F","Rexgen Inc."),
("2C265F","Appostar Technology Co. Ltd"),
("2C265F","Jiangsu JARI Technology Group Co., LTD"),
("2C265F","Griessbach"),
("F80278","Luxul Technology Inc"),
("28FD80","T-Radio AS"),
("74E14A","APM Technologies (DongGuan) Ltd"),
("74E14A","KLIMAT SOLEC Sp. z o.o."),
("E4956E","Tacom Projetos Bilhetagem Inteligente ltda"),
("D02212","AIM"),
("E81863","Acopian Technical Company"),
("E4956E","SMC Networks, Inc"),
("BC6641","Shenzhen Crave Communication Co.,ltd"),
("BC6641","VSN Mobil"),
("BC6641","Shenzhen Yaguang communication CO.,LTD"),
("D02212","Shanghai Routech Co., Ltd"),
("B8D812","VOTEM"),
("74E14A","Loctek Visual Technology Corp."),
("E4956E","eZeLink LLC"),
("E4956E","Shanghai DGE Co., Ltd"),
("E81863","ARTECH SOLUTION CO.,LTD"),
("E81863","clabsys"),
("B8D812","Yuwei Info&Tech Development Co.,Ltd"),
("B8D812","XIAMEN XINDECO LTD."),
("BC6641","Process-Electronic Sp. z o.o."),
("58FCDB","Applied Device Technologies"),
("58FCDB","SWARCO TRAFFIC SYSTEMS GMBH"),
("58FCDB","Xmodus Systems GmbH"),
("58FCDB","Certis Technology International"),
("58FCDB","Inforce Computing Inc."),
("58FCDB","Spang Power Electronics"),
("141FBA","Swiss Electronic (Shenzhen) Co., Ltd"),
("F40E11","BEIJING DONGJIN AERO-TECH CO., LTD"),
("141FBA","AJIS(DALIAN)co.,LTD"),
("141FBA","Black Moth Technologies"),
("141FBA","Shenzhen CATIC Information Technology Industry Co.,Ltd"),
("141FBA","Private"),
("141FBA","Deutsche Energieversorgung GmbH"),
("D07650","PelKorea"),
("D07650","Picobrew LLC"),
("7C70BC","mk-messtechnik GmbH"),
("7C70BC","Mennekes Elektrotechnik GmbH & Co. KG"),
("BC3400","Redvision CCTV"),
("A43BFA","ALSTOM Strongwish (Shenzhen) Co., Ltd"),
("B01F81","Dalian GigaTec Electronics Co.,Ltd"),
("F40E11","Kodpro Ltd."),
("F40E11","Alpha Design Technologies Pvt Ltd"),
("A43BFA","Alpwise"),
("D07650","Happo Solutions Oy"),
("7419F8","IDEXX Laboratories, Inc"),
("B01F81","CIDE Interactive"),
("B01F81","SHENZHEN YIFANG DIGITAL TECHNOLOGY CO.,LTD."),
("7C70BC","XD-GE Automation CO.,LTD"),
("BC3400","Parlay Labs dba Highfive"),
("BC3400","MATICA TECHNOLOGIES AG"),
("7419F8","Baudisch Electronic GmbH"),
("7419F8","Symtop Instrument Co."),
("1C8879","Shenzhen Xiaoxi Technology Co., Ltd."),
("1C8879","Toshiba Toko meter systems co., LTD."),
("1C8879","ITW-FEG"),
("1C8776","Artis GmbH"),
("1C8879","Newps co.,ltd"),
("1C8774","Xiaoxinge (Tangshan) Electronic Technology Co., Ltd."),
("1C8774","Surtec Industries, Inc"),
("1C8879","Orion Labs inc"),
("78CA83","Eksagate Elektronik Mühendislik ve Bilgisayar San. Tic. A.Ş."),
("78CA83","Zhejiang Science Electronic Tech Co., Ltd"),
("78CA83","Huatune Technology (Shanghai) Co., Ltd."),
("38B8EB","Bumjin C&L Co., Ltd."),
("38B8EB","Dojo-Labs Ltd"),
("38B8EB","1.A Connect GmbH"),
("38B8EB","SECAD SA"),
("38B8EB","Private"),
("38FDFE","Inspero Inc"),
("38FDFE","B.U.G.SST,Inc"),
("5CF286","Shenzhen VST Automotive Electronics Co., LTD"),
("7C477C","BlueSmart Technology Corporation"),
("7C477C","annapurnalabs"),
("986D35","Vitronic Dr.-Ing. Stein Bildverarbeitungssysteme GmbH"),
("7C477C","Shenzhen Eunicum Electric Co.,Ltd."),
("986D35","INTECH"),
("986D35","SHENZHEN FISE TECHNOLOGY HOLDING CO.,LTD."),
("50FF99","Simicon"),
("50FF99","Coyote Sytem"),
("50FF99","Sea Eagle Optoelectronic Information Technology(Tianjin)co,Ltd"),
("E0B6F5","Yuneec International（China）Co.，Ltd"),
("E0B6F5"," Shanghai- British Information Technology Co., Ltd"),
("E0B6F5","POMCube Inc. "),
("2C265F","AATON DIGITAL"),
("6891D0","NIPK Electron Co."),
("6891D0","Omniimpex GmbH"),
("6891D0","solvimus GmbH"),
("6891D0","femrice"),
("C47C8D","INOTEC Sicherheitstechnik GmbH"),
("C47C8D","ATI"),
("C47C8D","Anhui GuangXing Linked-Video Communication Technology Co, Ltd."),
("C47C8D","Labor Strauss Sicherungsanlagenbau GmbH"),
("CCD31E","inoage GmbH"),
("CCD31E","Haishu Technology LIMITED"),
("CCD31E","CUJO LLC"),
("D0D94F","Shenzhen FDC Electuonic Co.,Ltd."),
("D0D94F","DUKSANMECASYS CO., LTD."),
("D0D94F","mycable GmbH"),
("D0D94F","Beijing Yiwangxuntong Technology"),
("D0D94F","Apption Labs Limited"),
("D0D94F","Hyundai Autohow"),
("8C192D","Noritsu Precision Co., Ltd."),
("7C477C","Dspread Technology (Beijing) Inc."),
("1C8776","Dspread Technology (Beijing) Inc."),
("8C192D","ELCO(TIANJIN)ELECTRONICS CO.,LTD."),
("8C192D","TeleAlarm SA"),
("A03E6B","Private"),
("58FCDB","Private"),
("283638","Swisson AG"),
("E4956E","Private"),
("74F8DB","Private"),
("BC6641","Private"),
("74E14A","Private"),
("B8D812","Private"),
("2C265F","Private"),
("2C6A6F","Private"),
("64FB81","Private"),
("28FD80","Private"),
("A0BB3E","Private"),
("2CD141","Private"),
("283638","Havells India Limited"),
("84E0F4","PetroInTrade"),
("F0ACD7"," Guilin glsun Science and Tech Co.,LTD"),
("F0ACD7","Fiziico Co., Ltd."),
("58E876","Private"),
("58E876","Beijing Perabytes IS Technology Co., Ltd"),
("C0D391","Vernier Software & Technology"),
("C0D391","xxter bv"),
("C0D391","SAMSARA NETWORKS INC"),
("84E0F4","Logos01 Srl"),
("1C8774","Philips Personal Health Solutions"),
("1C8776","EBS Sp. z o.o."),
("1C8779","Shenzhen Innovaconn Systems Co.,Ltd"),
("1C8776","philandro Software GmbH"),
("8439BE","HINO ENGINEERING, INC"),
("40A36B","Amobile Intelligent Corp."),
("8439BE","Shenzhen IP3 Century Intelligent Technology Co., Ltd"),
("8439BE","Shenzhen Horn Audio Co.,Ltd."),
("40A36B","Pella Corporation"),
("40A36B","TOPROOTTechnology Corp. Ltd."),
("40A36B","PH Technical Labs"),
("70886B","CVnet"),
("70886B","Bitfinder Inc"),
("0055DA","Donguan WideLink Communication Technology Co.,Ltd."),
("0055DA","Arrow Electronics,Inc."),
("0055DA","Speechlab"),
("0055DA","Interaxon Inc"),
("0055DA","Beijing Connected Information Technology Co.,Ltd."),
("0055DA","Shinko Technos co.,ltd."),
("0055DA","KoolPOS Inc."),
("A03E6B","SinoGrid Software Systems Inc."),
("C88ED1","Ube, Inc. (dba Plum)"),
("A03E6B","Qunar.com"),
("A03E6B","Shenzhen Nufilo Inc."),
("B0C5CA","Private"),
("C88ED1","Linx Technologies"),
("1C21D1","Dynojet Research"),
("1C21D1","LG CNS"),
("1C21D1","Reliatronics Inc."),
("1C21D1","B-Scada Inc."),
("1C21D1","Toyo System CO.,LTD."),
("CC1BE0","Guangzhou Southelectric Power Science Technology Development Co.,Ltd."),
("CC1BE0","MDT technologies GmbH"),
("DC4427","Neusoft Corporation"),
("DC4427","Century Audio, Inc."),
("DC4427","Tesla Motors, Inc"),
("78C2C0","Shanghai Hanyi Technologies Co,.Ltd."),
("B0C5CA","EM-Tech"),
("74F8DB","Simon Electric (China) Co.,ltd"),
("74F8DB","Avantree Corporation"),
("74F8DB","Provision-ISR"),
("74F8DB","GHL Advanced Technology GmbH & Co. KG"),
("B437D1","Axiomatic Technologies Corporation"),
("B0C5CA","SYSTOVI"),
("549A11","Beijing HTSmartech Co.,Ltd"),
("549A11","eTauro LLC"),
("807B85","Interplan Co., Ltd."),
("90C682","Neone, Inc."),
("2C6A6F","SM DSP CO.,LTD."),
("80E4DA","CAVALRY STORAGE INC"),
("80E4DA","Guangzhou Pinzhong Electronic Technology CO., LTD"),
("2CD141","PIN SHANG LED Co., LTD."),
("2CD141","Fiberroad Technology Co., Ltd."),
("2CD141","Resus Industries"),
("1CCAE3","Shenzhen Smart Device Technology Co.,LTD"),
("1CCAE3","Sunray Medical Apparatus Co.,Ltd."),
("80E4DA","Elcus"),
("64FB81","MOBILUS Inc."),
("1CCAE3","SHIN-YOSHA CORPORATION"),
("2CD141","XiaMen 35.com Technology Co,.Ltd."),
("2CD141","IntelliLUM"),
("2CD141","Ezee Systems Limited"),
("90C682","Li Seng Technology Ltd."),
("64FB81","NPG Technology S.A."),
("885D90","Schmidt & Co.,(H.K.)Ltd."),
("885D90","CPAC Systems"),
("807B85","Phoenix Co.,Ltd."),
("0CEFAF","Syntrans AB"),
("A44F29","Neotech Systems Pvt. Ltd."),
("0CEFAF","Assurelink"),
("2C265F","Brüel & Kjaer Vibro GmbH"),
("2C265F","GTA Electronics Co., Ltd."),
("F80278","Technology Research, LLC"),
("F80278","Beijing Redcdn Technology, Co., Ltd"),
("A44F29","HTD"),
("A44F29","LUCEOR"),
("F80278","CLARUS Korea Co., Ltd"),
("F80278","Digatron Power Electronics GmbH"),
("0CEFAF","chengdu joyotime Technology Co., Ltd."),
("9802D8","EBI  Ltd."),
("9802D8","Stoerk-Tronic, Stoerk GmbH & Co.KG"),
("A0BB3E","Ewig Industries Macao Commercial Offshore Ltd"),
("A0BB3E","Xiamen Kehua Hengsheng Co.,Ltd"),
("2C6A6F","Cloudproject Generation Srl"),
("9802D8","Promicon Elektronik GmbH + Co.KG"),
("9802D8","Navroom Beijing, China"),
("A0BB3E","IVision Electronics Co.,Ltd"),
("28FD80","Apollo Digital (Taiwan) Ltd."),
("28FD80","Vigil Monitoring"),
("3C39E7","Attrackting AG"),
("3C39E7","University of British Columbia"),
("28FD80","University of York"),
("28FD80","Millcode"),
("2C265F","Hysentel Technology Co., Ltd"),
("B8D812","Visual Productions BV"),
("B8D812","IPM Sales and service Co.,Ltd."),
("74E14A","Knog Pty Ltd"),
("74E14A","Kanto Aircraft Instrument Co., Ltd."),
("BC6641","ARGUS-SPECTRUM"),
("58FCDB","XIAMEN LEELEN TECHNOLOGY CO.,LTD"),
("58FCDB","Shanghai Qianjin Electronic Equipment Co. Ltd"),
("100723","Beijing Assem Technology Co., ltd"),
("D02212","Schleifenbauer Holding BV"),
("D02212","Shenzhen SIC Technology. Co., Ltd."),
("100723","Fujian Quanzhou Dong Ang Electronics Co., Ltd."),
("100723","SHENZHEN XINFA ELECTRONIC CO.,LTD"),
("100723","BEIJING SOOALL INFORMATION TECHNOLOGY CO.,LTD"),
("100723","Diginet Control Systems Pty Ltd"),
("E4956E","SHENZHEN JOYETECH ELECTRONICS CO., LTD."),
("B8D812","Docobo Limited"),
("BC6641","EBlink"),
("E81863","Protek Electronics Group Co.,LTD"),
("74E14A","UTU Oy"),
("74E14A","Altenburger Electronic GmbH"),
("F40E11","NIHON MEGA LOGIC CO.,LTD."),
("F40E11","Zeepro Inc."),
("F40E11","Dayang Technology Development Inc."),
("141FBA","Newings Communication CO., LTD."),
("141FBA","Inttelix Brasil Tecnologia e Sistemas Ltda"),
("A43BFA","SHANGHAI XIETONG TECHNOLOGY INC."),
("A43BFA","Maxon Australia"),
("141FBA","GloQuad"),
("7C70BC","Nomad Digital Ltd."),
("7C70BC","Tohan　Engineering　Corporation"),
("A43BFA","Chengdu Territory Technology Co.,Ltd"),
("D07650","tecnotron elekronik gmbh"),
("D07650","Accumulate AB"),
("D07650","Private"),
("58FCDB","Custom Biogenic Systems"),
("B01F81","Rademacher Geraete-Elektronik GmbH"),
("BC3400","NDSL, Inc."),
("BC3400","Altronix Corporation"),
("B01F81","Aether Services, Inc."),
("B01F81","Sound United"),
("7C70BC","FLEXIM GmbH"),
("7419F8","Princip a.s."),
("7419F8","Starcor Beijing Co.,Limited"),
("D07650","CentrAlert, Inc."),
("7419F8","Ansjer Electronics Co., Ltd."),
("7419F8","Trend-tech Technology Co., Limited"),
("1C8774","CLABER SPA"),
("1C8774","Schawbel Technologies LLC"),
("1C8774","Nebbiolo Technologies"),
("78CA83","DAINCUBE"),
("38B8EB","UMLOGICS"),
("38B8EB","NHS Sistemas de Energia"),
("38FDFE","Management Service Corporation"),
("38FDFE","Swedish Adrenaline AB"),
("38FDFE","New Telecom Solutions LLC"),
("38FDFE","OOO Group of Industrial Technologies"),
("5CF286","Hangzhou Signwei Electronics Technology Co., Ltd"),
("5CF286","beijing your wonderful control system technology co.,ltd"),
("5CF286","EUROIMMUN Medizinische Labordiagnostika AG"),
("5CF286","iSon Tech"),
("7C477C","Zerosystem LTD.Co"),
("7C477C","Speedifi Inc"),
("986D35","Private"),
("986D35","DH Mechatronic AG"),
("986D35","PDAHL "),
("E0B6F5","Motiveprime Consumer Electronics Pvt Ltd"),
("E0B6F5","START TODAY CO.,LTD."),
("6891D0","QUANTEX"),
("6891D0","Fuzhou x-speed information technology Co.,Ltd."),
("6891D0","Ambitio LLC"),
("6891D0","Outstanding Technology Co., Ltd."),
("D0D94F","ARROWAVE TECHNOLOGIES LIMITED"),
("283638","Innovative Technology Ltd"),
("800A80","Private"),
("B437D1","Private"),
("0CEFAF","Private"),
("A44F29","Private"),
("78C2C0","Private"),
("141FBA","Private"),
("549A11","Private"),
("807B85","Private"),
("283638","Georg Neumann GmbH"),
("8C192D","Shenzhen Cylan Technology Co.,Ltd"),
("8C192D","DataRemote Inc."),
("D0D94F","APPOTRONICS CO., LTD"),
("8C192D","smartHome Partner GmbH"),
("78C2C0","SICHUAN TIANYI COMHEART TELECOMCO.,LTD"),
("8C192D","Abside Networks, Inc."),
("F0ACD7","Groupeer Technologies"),
("F0ACD7","Sercomm Corporation."),
("58E876","annapurnalabs"),
("58E876","SHENZHEN DIGISSIN TECHNOLOGY"),
("58E876","Coala Life AB"),
("C0D391","ALNETz Co.,LTD"),
("C0D391","XENA SECURITY LIMITED"),
("C0D391","Zhinengguo technology company limited"),
("84E0F4","Hangzhou Uni-Ubi Co.,Ltd.");