use org_uni_ids;

insert into manid (Company_id, organization) values
("1117","SKC Audio"),
("1111","DPA Microphones A/S"),
("1109","General Motors"),
("1104","UNIPULSE Corporation"),
("1101","yurbuds Sport Earphones"),
("104","Sentek Dynamics"),
("14908","Flintec"),
("7382","Druck- und Durchflussmessung"),
("1119","SIMTEC Elektronik GmbH"),
("1116","acam-messelectronic gmbh"),
("1113","Valens Semiconductor Ltd."),
("1106","Dynamic Systems Inc"),
("1099","ME-Messsysteme GmbH"),
("1098","Baker-Calling, Inc."),
("108","Ashcroft Inc"),
("88","Streamline Automation, LLC"),
("95","ACO, Co., Ltd"),
("89","NTI AG"),
("91","Fenda Technology Ltd."),
("96","B&W Sensing Technologies"),
("85","Adcon Telemetry GmbH"),
("92","A.S.T. Agewandte System Technik GmbH"),
("97","ETH-messtechnik gmbh"),
("86","LCM Systems Ltd"),
("93","Monitran"),
("98","Proctor & Chester Measurements Ltd"),
("87","SVANTEK Sp. z.o.o"),
("99","HEAD acoustics GmbH"),
("94","Test GmbH"),
("84","Natec Sensors GmbH"),
("81","Aikoh Engineering"),
("79","CEA"),
("82","Studio Technologies, Inc."),
("76","The Pinax Group, Inc."),
("77","Kulite Semiconductor Products Inc"),
("78","Showa Measuring Instruments Co., Ltd"),
("74","BSWA Technology Co., Ltd"),
("75","Sensordata Technologies, Inc."),
("83","Dewetron GmbH"),
("102","tecsis LP"),
("1108","CSM GmbH"),
("1103","LMS"),
("1100","Nakamura Mfg.Co.,Ltd"),
("105","IPETRONIK GmbH & Co.KG"),
("63","Mettler-Toledo GmbH Process Analytics"),
("68","VIP Sensors"),
("70","Druck Ltd."),
("64","MTS Systems Corp."),
("69","Sensy SA"),
("71","Tokyo Sokki Kenkyujo Co., Ltd"),
("65","Viatran Corporation"),
("61","Metra Mess-und Frequenztechnik Radebeul"),
("66","Sinocera Piezotronics, Inc."),
("62","Ametek Denmark A/S"),
("67","MSC Automotive Ltd"),
("56","Knick Elektronische Messgeraete GmbH Co. KG"),
("51","AVL List GmbH"),
("57","Lorenz Messtechnik GmbH"),
("52","Pressure Systems"),
("58","Kyowa Electronic Instruments Co., Ltd"),
("60","Sherborne Sensors Limited"),
("53","ONO SOKKI"),
("59","Interface, Inc."),
("54","imc MeBsysteme GmbH"),
("50","Waycon"),
("55","Futek Advanced Sensor Technology, Inc."),
("6457","CHENGDU CAIC ELECTRONICS CO.,LTD"),
("1110","Druck- und Durchflussmessung"),
("10799","SENTHER TECHNOLOGIES"),
("1112","Veridt, Inc"),
("1105","EnvyLogic Co.,Ltd."),
("103","YMC Piezotronics, Inc."),
("24","G.R.A.S. Sound & Vibration"),
("29","Scitefair International, Inc."),
("31","HBM"),
("36","SincoTec"),
("43","Measurement Specialties"),
("48","RDP Electronics"),
("18","The Modal Shop, Inc."),
("20","Macro Sensors"),
("25","Larson Davis"),
("32","TEAC"),
("37","Lebow"),
("44","Fuji Ceramics"),
("49","Sensorex"),
("19","Kistler Instrument Corporation"),
("21","Wilcoxon Research"),
("26","Key Transducers, Inc."),
("33","RION CO."),
("38","Celesco"),
("40","SensoTec"),
("45","Telemonitor"),
("22","Endevco Corporation"),
("27","Oceana Sensor Technologies"),
("34","Esensors"),
("39","Weed Instrument"),
("41","Watlow"),
("46","Lion Precision"),
("23","PCB Piezotronics, Inc."),
("28","Entek IRD"),
("30","National Instruments"),
("35","Dytran Instruments"),
("42","Transducer Techniques"),
("47","LEM"),
("100","LLC GlobalTest"),
("90","Ridgetop Group Inc."),
("80","Microtech Gefell GmbH"),
("1097","ETAS"),
("17","Bruel & Kjaer"),
("10700","Hangzhou Aihua Instruments Co., Ltd."),
("1115","MICRO-EPSILON MESSTECHNIK GmbH & Co. KG"),
("1120","DJB Instruments"),
("1107","DongHua Testing Technology Co., Ltd."),
("107","Tovey Engineering Inc"),
("73","Connection Technology Center"),
("106","Dewesoft d.o.o."),
("101","L.S. Starrett Company");